<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 2020/5/26
 * Time: 8:49
 */
global $_W;exit;
$schoolid = 41;
$weid = 1;
pdo_delete($this->table_icon, array('schoolid' => $schoolid,'place' => 3));
pdo_delete($this->table_icon, array('schoolid' => $schoolid,'place' => 4));
pdo_delete($this->table_icon, array('schoolid' => $schoolid,'place' => 5));
//顶部
$icon1 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'考勤','do' => 'calendar','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/parent_sign.png','url' => $this->createMobileUrl('calendar', array('schoolid' => $schoolid)),'place' => 3,'ssort' => 1,'status' => 1,);
$icon2 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'通知','do' => 'snoticelist','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/circle_icon1_2.png','url' => $this->createMobileUrl('snoticelist', array('schoolid' => $schoolid)),'place' => 3,'ssort' => 2,'status' => 1,);
$icon3 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'作业','do' => 'szuoyelist','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/circle_icon1_1.png','url' => $this->createMobileUrl('szuoyelist', array('schoolid' => $schoolid)),'place' => 3,'ssort' => 3,'status' => 1,);
$icon4 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'留言','do' => 'slylist','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/circle_icon1_5.png','url' => $this->createMobileUrl('slylist', array('schoolid' => $schoolid)),'place' => 3,'ssort' => 4,'status' => 1,);
//魔方
$icon5 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'本周计划','beizhu' =>'关注学生成长','do' => 'szjhlist','color' => '#ff0000','icon' => MODULE_URL.'public/mobile/img/3.png','url' => $this->createMobileUrl('szjhlist', array('schoolid' => $schoolid)),'place' => 4,'ssort' => 1,'status' => 1,);
$icon6 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'校园商城','beizhu' =>'校园周边','do' => 'sgoodslist','color' => '#ff9900','icon' => MODULE_URL.'public/mobile/img/1.png','url' => $this->createMobileUrl('sgoodslist', array('schoolid' => $schoolid)),'place' => 4,'ssort' => 2,'status' => 1,);
$icon7 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'班级相册','beizhu' =>'记录精彩瞬间','do' => 'sxclist','color' => '#6aa84f','icon' => MODULE_URL.'public/mobile/img/4.png','url' => $this->createMobileUrl('sxclist', array('schoolid' => $schoolid)),'place' => 4,'ssort' => 3,'status' => 1,);
$icon8 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'校园视频','beizhu' =>'实时关注孩子','do' => 'allcamera','color' => '#a64d79','icon' => MODULE_URL.'public/mobile/img/2.png','url' => $this->createMobileUrl('allcamera', array('schoolid' => $schoolid)),'place' => 4,'ssort' => 4,'status' => 1,);
//列表
$icon9 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'学生基本信息','do' => 'myinfo','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_icon3_4.png','url' => $this->createMobileUrl('myinfo', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 1,'status' => 1,);
$icon10 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'我的授课老师','do' => 'mytecher','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_use_icon1_2.png','url' => $this->createMobileUrl('mytecher', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 2,'status' => 1,);
$icon11 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'我的在读课程','do' => 'myclass','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_icon3_1.png','url' => $this->createMobileUrl('myclass', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 3,'status' => 1,);
$icon12 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'请假记录','do' => 'leavelist','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_icon4_9.png','url' => $this->createMobileUrl('leavelist', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 4,'status' => 1,);
$icon13 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'绑定考勤卡','do' => 'checkcard','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_icon4_9.png','url' => $this->createMobileUrl('checkcard', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 5,'status' => 1,);
$icon14 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'我的成绩','do' => 'chengji','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_icon4_8.png','url' => $this->createMobileUrl('chengji', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 6,'status' => 1,);
$icon15 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'本周课表','do' => 'timetable','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_icon2_1.png','url' => $this->createMobileUrl('timetable', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 7,'status' => 1,);
$icon16 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'车载轨迹','do' => 'schoolbus','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/czgj.png','url' => $this->createMobileUrl('schoolbus', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 8,'status' => 1,);
$icon17 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'在校表现','do' => 'sclistforxs','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_use_icon1_4.png','url' => $this->createMobileUrl('sclistforxs', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 9,'status' => 1,);
$icon18 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'集体活动','do' => 'galist','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_icon4_1.png','url' => $this->createMobileUrl('galist', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 10,'status' => 1,);
$icon19 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'意见反馈','do' => 'syzxx','color' => '#06c1ae','icon' => MODULE_URL.'public/mobile/img/hard_use_icon8_3.png','url' => $this->createMobileUrl('syzxx', array('schoolid' => $schoolid)),'place' => 5,'ssort' => 11,'status' => 1,);
pdo_insert($this->table_icon, $icon1);
pdo_insert($this->table_icon, $icon2);
pdo_insert($this->table_icon, $icon3);
pdo_insert($this->table_icon, $icon4);
pdo_insert($this->table_icon, $icon5);
pdo_insert($this->table_icon, $icon6);
pdo_insert($this->table_icon, $icon7);
pdo_insert($this->table_icon, $icon8);
pdo_insert($this->table_icon, $icon9);
pdo_insert($this->table_icon, $icon10);
pdo_insert($this->table_icon, $icon11);
pdo_insert($this->table_icon, $icon12);
pdo_insert($this->table_icon, $icon13);
pdo_insert($this->table_icon, $icon14);
pdo_insert($this->table_icon, $icon15);
pdo_insert($this->table_icon, $icon16);
pdo_insert($this->table_icon, $icon17);
pdo_insert($this->table_icon, $icon18);
pdo_insert($this->table_icon, $icon19);

$icon1 = array('weid' => $weid,'schoolid' => $id,'name' =>'学校简介','icon' => OSSURL.'public/mobile/img/ioc1.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('jianjie', array('schoolid' => $id)),'place' => 1,'ssort' => 1,'status' => 1,);
$icon2 = array('weid' => $weid,'schoolid' => $id,'name' =>'教师风采','icon' => OSSURL.'public/mobile/img/ioc2.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('teachers', array('schoolid' => $id)),'place' => 1,'ssort' => 2,'status' => 1,);
$icon3 = array('weid' => $weid,'schoolid' => $id,'name' =>'招生简介','icon' => OSSURL.'public/mobile/img/ioc4.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('zhaosheng', array('schoolid' => $id)),'place' => 1,'ssort' => 3,'status' => 1,);
$icon4 = array('weid' => $weid,'schoolid' => $id,'name' =>'本周食谱','icon' => OSSURL.'public/mobile/img/ioc3.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('cooklist', array('schoolid' => $id)),'place' => 1,'ssort' => 4,'status' => 1,);
$icon5 = array('weid' => $weid,'schoolid' => $id,'name' =>'微信绑定','icon' => OSSURL.'public/mobile/img/ioc7.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('bangding', array('schoolid' => $id)),'place' => 1,'ssort' => 5,'status' => 1,);
$icon6 = array('weid' => $weid,'schoolid' => $id,'name' =>'课程列表','icon' => OSSURL.'public/mobile/img/ioc8.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('kc', array('schoolid' => $id)),'place' => 1,'ssort' => 6,'status' => 1,);
$icon7 = array('weid' => $weid,'schoolid' => $id,'name' =>'报名申请','icon' => OSSURL.'public/mobile/img/ioc9.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('signup', array('schoolid' => $id)),'place' => 1,'ssort' => 7,'status' => 1,);
$icon8 = array('weid' => $weid,'schoolid' => $id,'name' =>'教师中心','icon' => OSSURL.'public/mobile/img/ioc10.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('myschool', array('schoolid' => $id)),'place' => 1,'ssort' => 8,'status' => 1,);
pdo_insert($this->table_icon, $icon1);
pdo_insert($this->table_icon, $icon2);
pdo_insert($this->table_icon, $icon3);
pdo_insert($this->table_icon, $icon4);
pdo_insert($this->table_icon, $icon5);
pdo_insert($this->table_icon, $icon6);
pdo_insert($this->table_icon, $icon7);
pdo_insert($this->table_icon, $icon8);
$schoolid = $id;
$icons1 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'校园','do' => 'detail','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon1_noSelect.png','icon2' => OSSURL.'public/mobile/img/bottom_menu_icon1_Select.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('detail', array('schoolid' => $schoolid)),'place' => 6,'ssort' => 1,'status' => 1,);
$icons2 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'班级圈','do' => 'sbjq','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon2_noSelect.png','icon2' => OSSURL.'public/mobile/img/bottom_menu_icon2_Select.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('sbjq', array('schoolid' => $schoolid)),'place' => 6,'ssort' => 2,'status' => 1,);
$icons3 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'通讯录','do' => 'callbook','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon3_noSelect.png','icon2' => OSSURL.'public/mobile/img/bottom_menu_icon3_Select.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('callbook', array('schoolid' => $schoolid)),'place' => 6,'ssort' => 4,'status' => 1,);
$icons4 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'我的','do' => 'user','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon4_noSelect.png','icon2' => OSSURL.'public/mobile/img/bottom_menu_icon4_Select.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('user', array('schoolid' => $schoolid)),'place' => 6,'ssort' => 5,'status' => 1,);
//学生弹框
$icons5 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'请假','color' => '#EAEAEA','icon' => OSSURL.'public/mobile/img/ionc_1.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('xsqj', array('schoolid' => $schoolid)),'place' => 7,'ssort' => 1,'status' => 1,);
$icons6 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'留言','color' => '#F6F4F4','icon' => OSSURL.'public/mobile/img/ionc_2.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('slylist', array('schoolid' => $schoolid)),'place' => 7,'ssort' => 2,'status' => 1,);
$icons7 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'发动态','color' => '#EAEAEA','icon' => OSSURL.'public/mobile/img/ionc_3.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('sbjqfabu', array('schoolid' => $schoolid)),'place' => 7,'ssort' => 3,'status' => 1,);
$icons8 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'传照片','color' => '#F6F4F4','icon' => OSSURL.'public/mobile/img/ionc_4.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('sxcfb', array('schoolid' => $schoolid)),'place' => 7,'ssort' => 4,'status' => 1,);
//教师底部
$icons9 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'校园','do' => 'detail','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon1_noSelect.png','icon2' => OSSURL.'public/mobile/img/bottom_menu_icon1_Select.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('detail', array('schoolid' => $schoolid)),'place' => 8,'ssort' => 1,'status' => 1,);
$icons10 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'班级圈','do' => 'bjq','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon2_noSelect.png','icon2' => OSSURL.'public/mobile/img/bottom_menu_icon2_Select.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('bjq', array('schoolid' => $schoolid)),'place' => 8,'ssort' => 2,'status' => 1,);
$icons11 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'通讯录','do' => 'tongxunlu','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon3_noSelect.png','icon2' => OSSURL.'public/mobile/img/bottom_menu_icon3_Select.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('tongxunlu', array('schoolid' => $schoolid)),'place' => 8,'ssort' => 4,'status' => 1,);
$icons12 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'我的','do' => 'myschool','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon4_noSelect.png','icon2' => OSSURL.'public/mobile/img/bottom_menu_icon4_Select.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('myschool', array('schoolid' => $schoolid)),'place' => 8,'ssort' => 5,'status' => 1,);
//教师弹框
$icons13 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'发布作业','color' => '#EAEAEA','icon' => OSSURL.'public/mobile/img/ionc_1.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('zfabu', array('schoolid' => $schoolid)),'place' => 9,'ssort' => 1,'status' => 1,);
$icons14 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'发通知','color' => '#F6F4F4','icon' => OSSURL.'public/mobile/img/ionc_2.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('fabu', array('schoolid' => $schoolid)),'place' => 9,'ssort' => 2,'status' => 1,);
$icons15 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'发动态','color' => '#EAEAEA','icon' => OSSURL.'public/mobile/img/ionc_3.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('bjqfabu', array('schoolid' => $schoolid)),'place' => 9,'ssort' => 3,'status' => 1,);
$icons16 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'传照片','color' => '#F6F4F4','icon' => OSSURL.'public/mobile/img/ionc_4.png','url' => $_W['siteroot'] .'app/'.$this->createMobileUrl('xcfb', array('schoolid' => $schoolid)),'place' => 9,'ssort' => 4,'status' => 1,);
$icon17 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'中心按钮','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon_add.png','place' => 10,'ssort' => 0,'status' => 1,);
$icon18 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'中心按钮','color' => '#06c1ae','icon' => OSSURL.'public/mobile/img/bottom_menu_icon_add.png','place' => 11,'ssort' => 0,'status' => 1,);
pdo_insert($this->table_icon, $icons1);
pdo_insert($this->table_icon, $icons2);
pdo_insert($this->table_icon, $icons3);
pdo_insert($this->table_icon, $icons4);
pdo_insert($this->table_icon, $icons5);
pdo_insert($this->table_icon, $icons6);
pdo_insert($this->table_icon, $icons7);
pdo_insert($this->table_icon, $icons8);
pdo_insert($this->table_icon, $icons9);
pdo_insert($this->table_icon, $icons10);
pdo_insert($this->table_icon, $icons11);
pdo_insert($this->table_icon, $icons12);
pdo_insert($this->table_icon, $icons13);
pdo_insert($this->table_icon, $icons14);
pdo_insert($this->table_icon, $icons15);
pdo_insert($this->table_icon, $icons16);
pdo_insert($this->table_icon, $icon17);
pdo_insert($this->table_icon, $icon18);
$icon21  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'留言','icon' => MODULE_URL.'public/mobile/img/link_msg.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('tlylist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tlylist', 'ssort' => 1,'status' => 1,);
$icon22  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'班级通知','icon' => MODULE_URL.'public/mobile/img/link_bjtz.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('noticelist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'noticelist','ssort' => 2,'status' => 1,);
$icon23  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'学生请假','icon' => MODULE_URL.'public/mobile/img/link_ktdt.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('smssage', array('schoolid' => $schoolid)),'place' => 13,'do'=>'smssage','ssort' => 3,'status' => 1,);
$icon24  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'商城','icon' => MODULE_URL.'public/mobile/img/link_mail.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('goodslist', array('schoolid' => $schoolid)),'place' =>13, 'do'=>'goodslist','ssort' => 4,'status' => 1,);
$icon25  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'任务','icon' => MODULE_URL.'public/mobile/img/circle_icon1_7.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('todolist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'todolist','ssort' => 5,'status' => 1,);
$icon26  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'课程预约','icon' => MODULE_URL.'public/mobile/img/circle_icon18.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('cyylist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'cyylist','ssort' => 6,'status' => 1,);
$icon27  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'我的课程','icon' => MODULE_URL.'public/mobile/img/circle_icon1_1.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('tmycourse', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tmycourse','ssort' => 7,'status' => 1,);
$icon28  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'授课情况','icon' => MODULE_URL.'public/mobile/img/circle_icon15.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('tkcsignall', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tkcsignall','ssort' => 8,'status' => 1,);
$icon29  = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'我的公开课','icon' => MODULE_URL.'public/mobile/img/circle_icon18.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('gkklist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'gkklist','ssort' => 9,'status' => 1,);
$icon210 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'评价的公开课','icon' => MODULE_URL.'public/mobile/img/circle_icon711.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('gkkpjjl', array('schoolid' => $schoolid)),'place' => 13,'do'=>'gkkpjjl','ssort' => 10,'status' => 1,);
$icon211 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'校长信箱','icon' => MODULE_URL.'public/mobile/img/circle_icon16.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('tyzxx', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tyzxx','ssort' => 11,'status' => 1,);
$icon212 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'职工请假','icon' => MODULE_URL.'public/mobile/img/circle_icon1_3.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('tmssage', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tmssage','ssort' => 12,'status' => 1,);
$icon213 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'校园公告','icon' => MODULE_URL.'public/mobile/img/link_alarm.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('mnoticelist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'mnoticelist','ssort' => 13,'status' => 1,);
$icon214 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'作业管理','icon' => MODULE_URL.'public/mobile/img/link_zuoye.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('zuoyelist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'zuoyelist','ssort' => 14,'status' => 1,);
$icon215 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'一键放学','icon' => MODULE_URL.'public/mobile/img/link_fx.png','url' => '','place' => 13,'do'=>'yjfx','ssort' => 15,'status' => 1,);
$icon216 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'班级圈','icon' => MODULE_URL.'public/mobile/img/link_bjq.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('bjq', array('schoolid' => $schoolid)),'place' => 13,'do'=>'bjq','ssort' => 16,'status' => 1,);
$icon217 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'班级相册','icon' => MODULE_URL.'public/mobile/img/link_xc.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('xclist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'xclist','ssort' => 17,'status' => 1,);
$icon218 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'学生管理','icon' => MODULE_URL.'public/mobile/img/link_xs.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('stulist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'stulist','ssort' => 18,'status' => 1,);
$icon219 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'报名列表','icon' => MODULE_URL.'public/mobile/img/link_bm.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('bmlist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'bmlist','ssort' => 19,'status' => 1,);
$icon220 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'学生考勤','icon' => MODULE_URL.'public/mobile/img/link_sck.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('signlist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'signlist','ssort' => 20,'status' => 1,);
$icon221 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'职工考勤','icon' => MODULE_URL.'public/mobile/img/link_jskq.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('jschecklog', array('schoolid' => $schoolid)),'place' => 13,'do'=>'jschecklog','ssort' => 21,'status' => 1,);
$icon222 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'通讯录','icon' => MODULE_URL.'public/mobile/img/ioc11.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('tongxunlu', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tongxunlu','ssort' => 22,'status' => 1,);
$icon223 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'周计划','icon' => MODULE_URL.'public/mobile/img/link_zjh.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('tzjhlist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tzjhlist','ssort' => 23,'status' => 1,);
$icon224 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'成长手册','icon' => MODULE_URL.'public/mobile/img/link_zxbx.png','url' => $_W['siteroot'] .'app/'.$this -> createMobileUrl('shoucelist', array('schoolid' => $schoolid)),'place' => 13,'do'=>'shoucelist','ssort' => 24,'status' => 1,);
$icon225 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'我的评分','icon' => MODULE_URL.'public/mobile/img/circle_icon4.png','url' =>$_W['siteroot'] .'app/'.$this -> createMobileUrl('tmyscore', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tmyscore','ssort' => 25,'status' => 1,);
$icon226 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'评分情况','icon' => MODULE_URL.'public/mobile/img/formal_enroll_icon.png','url' =>$_W['siteroot'] .'app/'.$this -> createMobileUrl('tscoreall', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tscoreall','ssort' => 26,'status' => 1,);
$icon227 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'学生评分','icon' => MODULE_URL.'public/mobile/img/circle_icon17.png','url' => $this -> createMobileUrl('tstuscore', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tstuscore','ssort' => 27,'status' => 1,);
$icon228 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'宿舍考勤','icon' => MODULE_URL.'public/mobile/img/circle_icon23.png','url' => $this -> createMobileUrl('tstuapinfo', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tstuscore','ssort' => 28,'status' => 1,);
$icon230 = array('weid' => $weid,'schoolid' => $schoolid,'name' =>'监控列表','icon' => MODULE_URL.'public/mobile/img/59ddef4d7a25b_88.png','url' => $this -> createMobileUrl('tallcamera', array('schoolid' => $schoolid)),'place' => 13,'do'=>'tallcamera','ssort' => 30,'status' => 1,);
pdo_insert($this->table_icon, $icon21);
pdo_insert($this->table_icon, $icon22);
pdo_insert($this->table_icon, $icon23);
pdo_insert($this->table_icon, $icon24);
pdo_insert($this->table_icon, $icon25);
pdo_insert($this->table_icon, $icon26);
pdo_insert($this->table_icon, $icon27);
pdo_insert($this->table_icon, $icon28);
pdo_insert($this->table_icon, $icon29);
pdo_insert($this->table_icon, $icon210);
pdo_insert($this->table_icon, $icon211);
pdo_insert($this->table_icon, $icon212);
pdo_insert($this->table_icon, $icon213);
pdo_insert($this->table_icon, $icon214);
pdo_insert($this->table_icon, $icon215);
pdo_insert($this->table_icon, $icon216);
pdo_insert($this->table_icon, $icon217);
pdo_insert($this->table_icon, $icon218);
pdo_insert($this->table_icon, $icon219);
pdo_insert($this->table_icon, $icon220);
pdo_insert($this->table_icon, $icon221);
pdo_insert($this->table_icon, $icon222);
pdo_insert($this->table_icon, $icon223);
pdo_insert($this->table_icon, $icon224);
pdo_insert($this->table_icon, $icon225);
pdo_insert($this->table_icon, $icon226);
pdo_insert($this->table_icon, $icon227);
pdo_insert($this->table_icon, $icon228);
pdo_insert($this->table_icon, $icon230);